MODEL:
  ARCHITECTURE: "G2L"
  G2L:
    NUM_CLIPS: 128
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8,8]
    TEXT_ENCODER:
      NAME: 'BERT'
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.7
      NUM_POSTIVE_VIDEO_PROPOSAL: 3
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.1
      CONTRASTIVE_WEIGHT: 0.1
      AS_CL_WEIGHT: 1.0
      AS_CL: False
      GEO_K : 5
      GEO_TOPK : 5
      GEO_W : 0.0
      HARD_GEO_W: 1.0
      SHAPLEY_W: 0.0005
      SHAPLEY: False
DATASETS:
  NAME: "tacos"
  TRAIN: ("tacos_train",)
  TEST: ("tacos_test",)
INPUT:
  NUM_PRE_CLIPS: 256
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  # LR: 0.0015
  # BATCH_SIZE: 48
  # MILESTONES: (130, 190)
  # MAX_EPOCH: 250
  # TEST_PERIOD: 10
  # CHECKPOINT_PERIOD: 50
  # RESUME: False
  # RESUME_EPOCH: 101
  # FREEZE_BERT: 40
  # ONLY_IOU: 100
  # SKIP_TEST: 0

  LR_SCHEDULER: "warmup_multistep"
  LR: 0.0008
  BATCH_SIZE: 8
  MILESTONES: (20, 30,40,60,80)
  WARMUP_EPOCHS: 30
  MAX_EPOCH: 250
  TEST_PERIOD: 5
  CHECKPOINT_PERIOD: 50
  RESUME: False
  RESUME_EPOCH: 101
  FREEZE_BERT: 40
  ONLY_IOU: 50
  SKIP_TEST: 0

TEST:
  NMS_THRESH: 0.4
  BATCH_SIZE: 16
  CONTRASTIVE_SCORE_POW: 0.3

